declare class OEM_ELEMENT<T extends HTMLElement> {
    #private;
    constructor(tag: string);
    private _applyAttributes;
    private _applyClassNames;
    private _applyStyles;
    private _applyListeners;
    private _applyNodes;
    private _applyInnerText;
    private _applyInnerHTML;
    private _createElement;
    addEventListener<E extends keyof GlobalEventHandlers>(ev: E, cb: (e: Event) => any): this;
    append(...nodes: (string | Node)[]): T;
    attr(name: string, val: string | (() => string), condition?: boolean | (() => boolean)): this;
    className(className: string, condition?: boolean | (() => boolean)): this;
    innerHTML(html: HTMLElement | (() => HTMLElement)): T;
    innerText(text: (string | number) | (() => string | number)): T;
    render(): T;
    subscribe(subscriptionFunction: (cb: () => void) => void, handler?: (el: ThisType<OEM_ELEMENT<T>>) => void): this;
    style(prop: keyof CSSStyleDeclaration, val: string | (() => string), condition?: boolean | (() => boolean) | "hover"): this;
}
export declare const A: OEM_ELEMENT<HTMLAnchorElement>;
export declare const AREA: OEM_ELEMENT<HTMLAreaElement>;
export declare const ARTICLE: OEM_ELEMENT<HTMLElement>;
export declare const ASIDE: OEM_ELEMENT<HTMLElement>;
export declare const AUDIO: OEM_ELEMENT<HTMLAudioElement>;
export declare const B: OEM_ELEMENT<HTMLElement>;
export declare const BASE: OEM_ELEMENT<HTMLBaseElement>;
export declare const BDI: OEM_ELEMENT<HTMLElement>;
export declare const BDO: OEM_ELEMENT<HTMLElement>;
export declare const BLOCKQUOTE: OEM_ELEMENT<HTMLQuoteElement>;
export declare const BODY: OEM_ELEMENT<HTMLBodyElement>;
export declare const BR: OEM_ELEMENT<HTMLBRElement>;
export declare const BUTTON: OEM_ELEMENT<HTMLButtonElement>;
export declare const CANVAS: OEM_ELEMENT<HTMLCanvasElement>;
export declare const CAPTION: OEM_ELEMENT<HTMLTableCaptionElement>;
export declare const CITE: OEM_ELEMENT<HTMLElement>;
export declare const CODE: OEM_ELEMENT<HTMLElement>;
export declare const COL: OEM_ELEMENT<HTMLTableColElement>;
export declare const COLGROUP: OEM_ELEMENT<HTMLTableColElement>;
export declare const DATA: OEM_ELEMENT<HTMLDataElement>;
export declare const DATALIST: OEM_ELEMENT<HTMLDataListElement>;
export declare const DD: OEM_ELEMENT<HTMLElement>;
export declare const DEL: OEM_ELEMENT<HTMLModElement>;
export declare const DETAILS: OEM_ELEMENT<HTMLDetailsElement>;
export declare const DFN: OEM_ELEMENT<HTMLElement>;
export declare const DIALOG: OEM_ELEMENT<HTMLDialogElement>;
export declare const DIV: OEM_ELEMENT<HTMLDivElement>;
export declare const DL: OEM_ELEMENT<HTMLDListElement>;
export declare const DT: OEM_ELEMENT<HTMLElement>;
export declare const EM: OEM_ELEMENT<HTMLElement>;
export declare const EMBED: OEM_ELEMENT<HTMLEmbedElement>;
export declare const FIELDSET: OEM_ELEMENT<HTMLFieldSetElement>;
export declare const FIGCAPTION: OEM_ELEMENT<HTMLElement>;
export declare const FIGURE: OEM_ELEMENT<HTMLElement>;
export declare const FOOTER: OEM_ELEMENT<HTMLElement>;
export declare const FORM: OEM_ELEMENT<HTMLFormElement>;
export declare const H1: OEM_ELEMENT<HTMLHeadElement>;
export declare const H2: OEM_ELEMENT<HTMLHeadElement>;
export declare const H3: OEM_ELEMENT<HTMLHeadElement>;
export declare const H4: OEM_ELEMENT<HTMLHeadElement>;
export declare const H5: OEM_ELEMENT<HTMLHeadElement>;
export declare const H6: OEM_ELEMENT<HTMLHeadElement>;
export declare const HEAD: OEM_ELEMENT<HTMLHeadElement>;
export declare const HEADER: OEM_ELEMENT<HTMLElement>;
export declare const HGROUP: OEM_ELEMENT<HTMLElement>;
export declare const HR: OEM_ELEMENT<HTMLHRElement>;
export declare const HTML: OEM_ELEMENT<HTMLElement>;
export declare const I: OEM_ELEMENT<HTMLElement>;
export declare const IFRAME: OEM_ELEMENT<HTMLElement>;
export declare const IMG: OEM_ELEMENT<HTMLElement>;
export declare const INPUT: OEM_ELEMENT<HTMLInputElement>;
export declare const INS: OEM_ELEMENT<HTMLElement>;
export declare const KBD: OEM_ELEMENT<HTMLElement>;
export declare const LABEL: OEM_ELEMENT<HTMLElement>;
export declare const LEGEND: OEM_ELEMENT<HTMLElement>;
export declare const LI: OEM_ELEMENT<HTMLElement>;
export declare const LINK: OEM_ELEMENT<HTMLElement>;
export declare const MAIN: OEM_ELEMENT<HTMLElement>;
export declare const MAP: OEM_ELEMENT<HTMLElement>;
export declare const MARK: OEM_ELEMENT<HTMLElement>;
export declare const MENU: OEM_ELEMENT<HTMLElement>;
export declare const META: OEM_ELEMENT<HTMLElement>;
export declare const METER: OEM_ELEMENT<HTMLElement>;
export declare const NAV: OEM_ELEMENT<HTMLElement>;
export declare const NOSCRIPT: OEM_ELEMENT<HTMLElement>;
export declare const OBJECT: OEM_ELEMENT<HTMLElement>;
export declare const OL: OEM_ELEMENT<HTMLElement>;
export declare const OPTGROUP: OEM_ELEMENT<HTMLElement>;
export declare const OPTION: OEM_ELEMENT<HTMLElement>;
export declare const OUTPUT: OEM_ELEMENT<HTMLElement>;
export declare const P: OEM_ELEMENT<HTMLElement>;
export declare const PICTURE: OEM_ELEMENT<HTMLElement>;
export declare const PRE: OEM_ELEMENT<HTMLElement>;
export declare const PROGRESS: OEM_ELEMENT<HTMLElement>;
export declare const Q: OEM_ELEMENT<HTMLElement>;
export declare const RP: OEM_ELEMENT<HTMLElement>;
export declare const RT: OEM_ELEMENT<HTMLElement>;
export declare const RUBY: OEM_ELEMENT<HTMLElement>;
export declare const S: OEM_ELEMENT<HTMLElement>;
export declare const SAMP: OEM_ELEMENT<HTMLElement>;
export declare const SCRIPT: OEM_ELEMENT<HTMLElement>;
export declare const SECTION: OEM_ELEMENT<HTMLElement>;
export declare const SELECT: OEM_ELEMENT<HTMLElement>;
export declare const SLOT: OEM_ELEMENT<HTMLElement>;
export declare const SMALL: OEM_ELEMENT<HTMLElement>;
export declare const SOURCE: OEM_ELEMENT<HTMLElement>;
export declare const SPAN: OEM_ELEMENT<HTMLElement>;
export declare const STRONG: OEM_ELEMENT<HTMLElement>;
export declare const STYLE: OEM_ELEMENT<HTMLElement>;
export declare const SUB: OEM_ELEMENT<HTMLElement>;
export declare const SUMMARY: OEM_ELEMENT<HTMLElement>;
export declare const SUP: OEM_ELEMENT<HTMLElement>;
export declare const TABLE: OEM_ELEMENT<HTMLElement>;
export declare const TBODY: OEM_ELEMENT<HTMLElement>;
export declare const TD: OEM_ELEMENT<HTMLElement>;
export declare const TEMPLATE: OEM_ELEMENT<HTMLElement>;
export declare const TEXTAREA: OEM_ELEMENT<HTMLElement>;
export declare const TFOOT: OEM_ELEMENT<HTMLElement>;
export declare const TH: OEM_ELEMENT<HTMLElement>;
export declare const THEAD: OEM_ELEMENT<HTMLElement>;
export declare const TIME: OEM_ELEMENT<HTMLElement>;
export declare const TITLE: OEM_ELEMENT<HTMLElement>;
export declare const TR: OEM_ELEMENT<HTMLElement>;
export declare const TRACK: OEM_ELEMENT<HTMLElement>;
export declare const U: OEM_ELEMENT<HTMLElement>;
export declare const UL: OEM_ELEMENT<HTMLElement>;
export declare const VAR: OEM_ELEMENT<HTMLElement>;
export declare const VIDEO: OEM_ELEMENT<HTMLElement>;
export declare const WBR: OEM_ELEMENT<HTMLElement>;
export {};
